// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboard() {
  return window['go']['app']['App']['GetDashboard']();
}

export function GetStock() {
  return window['go']['app']['App']['GetStock']();
}

export function GetTopItems() {
  return window['go']['app']['App']['GetTopItems']();
}

export function GetTurnoverByWarehouse() {
  return window['go']['app']['App']['GetTurnoverByWarehouse']();
}
