// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dashboard} from '../models';
import {model} from '../models';

export function GetDashboard():Promise<dashboard.DashboardData>;

export function GetStock():Promise<Array<model.Stock>>;

export function GetTopItems():Promise<Array<model.ItemWithStock>>;

export function GetTurnoverByWarehouse():Promise<Array<model.ItemTurnoverByWarehouse>>;
